language: scala

# These directories are cached at the end of the build
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jobs:
  include:

    - stage: style
      name: "Code style"
      script: sbt scalafmtCheck

    - stage: test
      script: sbt +test
      name: "Tests"
    - script: sbt makeSite
      name: "Documentation"
    - script: sbt mimaReportBinaryIssues
      name: "Binary compatibility"

    - stage: publish
      if: tag =~ ^v
      name: "Publish a release"
      script:
        # decrypt PGP secret key and GitHub SSH key
        - openssl aes-256-cbc -K $encrypted_602f530300eb_key -iv $encrypted_602f530300eb_iv -in ci/secrets.tar.enc -out ci/secrets.tar -d
        - tar xvf ci/secrets.tar
        - chmod 600 ci/travis-key
        - eval "$(ssh-agent -s)"
        - ssh-add ci/travis-key
        # perform deployment
        - sbt mimaReportBinaryIssues makeSite +publishSigned sonatypeRelease ghpagesPushSite

# credentials for publishing releases to Sonatype
env:
  global:
  - secure: SQuzT/S4uiRxf3qedqFH4Gs6q+JnZQbX88zDkNAgAY02WWoRzHWa7NiL2lwzEF6Aptp19K3aht3hGXOWmlPWcRLCo8gHA4eiFzSu09S3TqkYA0g6HvbtiyP6PzorDgyHpRRAzXMbTZEeyJ9YDcRwod+VR0EeNUFWbh+04CXcRNJDvQzfvgElCxAFQjcuZV3B37vENFPP4McWCEaaQsJekcorLSmYwfGIXFZOIXv+CPfF6cXi15zvtGn6xFDA4Auj0KrupLyjWNFfCE1cPekt2J7XuJ+5QKzINn1FUWHhiFrnB+2Q8bdh+ZosYGRAx7HKme7LkNKSOOjC7F5hkLkRjsWt4OI365Z5c7iw6GFCEnA7oMTs2NeCmHsS5gZLWOtOL8qrWoph87d8pmju7rFlwKx8aiMHoHGJVxiel9W3G0puaLyrp6G7Ym5PKHgiylqgFsfi8BbM6+e8dfX3hODhPLuiE+rLxHFELEFuBWzw/lJHQSgTB3F0QvHv4v3jJ0V87ejRGKU4SuUydkdGASl8jLPtzDHW6PPqx+FnPCWP5siU/tLDnbrlUPFbiVT2rIdgaSJHpkHdP2cgxxhZkuqydattlkK42iPB0dGeoEKlmIlfpLYCIcI78uaDfu4U6e/dJTlW2MFk+G3Fd0DXED+P4kDyF0fMt7W/K9lZNP4CbiY=
  - secure: Rj6cdhXwbvydrFCqutaa7wsmWy017d2/JW+Rcyj2q1pCCmnbMQy+9E5rIkhJcehwFkRaURvhRw90MhhoepeBf4elywjTU+F4rlQoxGdDtMzSNHoQbzNGZGL5KIUOtgAQlZe4QWXFpqAP4RKYdn+WsbZ20Jnvdpmny9IvERS0CR5y7s8pnKwLrSowQ8mCrsMYZ4pCDmNnS8K8ec7LNLSKLs2R1OE0GVPMXZpve7oANuoJoTWrxnslo5zAwHEoM6AU1QE4V/O3XSRsuytQyIOIpZxkU8fQImCMYDzjfFPx5REAjMdGr4e2lBGGDyLb11HhqQoIqeQeZbCTC02sndce0SljUy1XtjrPa2chHSuPVlGycfEkkbsMoHI23NHTuTs+aP+fZ7+Xb1KR5rIwhrcWvHGW+34EiL8MtGPRAFIwm/atR+IM4LgobI1HT4SN2uGmOaFRBhnHCNVNUy1iSxzMSbr9jhjop52MMEnHV/xazFyLEBPzF9nKcYUKCd6EaHVDNNcjC4o1IosJopS2BmTxmhkd39tGrEvMraMuLvN39cBep/RCabxa0kIrTghZMBFWXCuqGR2WWSvnfMHiKPqBK/73D3qpLDKLcN55S6VN03f1J7PDYO7VIx5wFHIx3mVIQlQj9r9draO/FiOc/IVDLYwMg4EQc+unNSgFhRLt4YU=
